apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pg-deploy
  name: pg-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pg-deploy
status:
  loadBalancer: {}
